development:
  sessions:
    default:
      database: lbyronlee_news_development
      hosts:
        - localhost:27017
      options:
  options:

test:
  sessions:
    default:
      database: lbyronlee_news_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0


production:
  sessions:
    default:
      database: lbyronlee_news
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
